esphome:
  name: qbbr_esp01s_1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.153
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Qbbr Esp01S 1 Fallback Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_ota_password

ota:
  password: !secret api_ota_password

#web_server:
#  port: 80

#text_sensor:
#  - platform: version
#    name: "qbbr_esp01s_1 ver"

binary_sensor:
  - platform: status
    name: "qbbr_esp01s_1 status"

switch:
  - platform: gpio
    pin: GPIO0
    name: "qbbr_esp01s_1 relay"
    inverted: true
  - platform: gpio
    pin: GPIO2
    name: "qbbr_esp01s_1 relay 2"
    inverted: true

#  - platform: gpio
#    pin: GPIO1
#    name: "qbbr_esp01s_1 led blue"
#    inverted: true
